[2016-11-25 15:59:33,234] [INFO] connectionpool : Starting new HTTP connection (1): up.qiniu.com
[2016-11-25 16:00:24,851] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 677, in get
    logger.error(u'瑙嗛杞珿IF澶辫触锛? + e)
TypeError: coercing to Unicode: need string or buffer, MultiValueDictKeyError found
[2016-11-25 16:00:24,851] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 677, in get
    logger.error(u'瑙嗛杞珿IF澶辫触锛? + e)
TypeError: coercing to Unicode: need string or buffer, MultiValueDictKeyError found
[2016-11-25 16:01:11,513] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 677, in get
    logger.error(u'瑙嗛杞珿IF澶辫触锛? + e)
TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found
[2016-11-25 16:01:11,513] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 677, in get
    logger.error(u'瑙嗛杞珿IF澶辫触锛? + e)
TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found
[2016-11-25 16:01:37,516] [ERROR] views : 'local_path21'
[2016-11-25 16:01:37,516] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 679, in get
    return HttpResponse(json.dumps({"status":"false","msg":u"瑙嗛杞珿IF鍑洪敊" + e}),content_type="application/json")
TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found
[2016-11-25 16:01:37,516] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 679, in get
    return HttpResponse(json.dumps({"status":"false","msg":u"瑙嗛杞珿IF鍑洪敊" + e}),content_type="application/json")
TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found
[2016-11-25 16:02:30,990] [ERROR] views : 'local_path21'
[2016-11-25 16:02:30,992] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 679, in get
    return HttpResponse(json.dumps({"status":"false","msg":"瑙嗛杞珿IF鍑洪敊" + e}),content_type="application/json")
TypeError: cannot concatenate 'str' and 'exceptions.KeyError' objects
[2016-11-25 16:02:30,992] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 679, in get
    return HttpResponse(json.dumps({"status":"false","msg":"瑙嗛杞珿IF鍑洪敊" + e}),content_type="application/json")
TypeError: cannot concatenate 'str' and 'exceptions.KeyError' objects
[2016-11-25 16:02:50,664] [ERROR] views : 'local_path21'
[2016-11-25 16:02:50,664] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 679, in get
    return HttpResponse(json.dumps({"status":"false","msg":e}),content_type="application/json")
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: KeyError('local_path21',) is not JSON serializable
[2016-11-25 16:02:50,664] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 679, in get
    return HttpResponse(json.dumps({"status":"false","msg":e}),content_type="application/json")
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: KeyError('local_path21',) is not JSON serializable
[2016-11-25 16:03:00,372] [ERROR] views : 'local_path21'
[2016-11-25 16:03:00,372] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 679, in get
    return HttpResponse(json.dumps({"status":"false","msg":e}),content_type="application/json")
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: KeyError('local_path21',) is not JSON serializable
[2016-11-25 16:03:00,372] [ERROR] base : Internal Server Error: /img/video2gif/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.8.5-py2.7.egg\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CarcerWorld\code\Python\git\image_str\image_server\wx_app\views.py", line 679, in get
    return HttpResponse(json.dumps({"status":"false","msg":e}),content_type="application/json")
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: KeyError('local_path21',) is not JSON serializable
[2016-11-25 16:03:31,118] [ERROR] views : 'local_path21'
[2016-11-25 16:04:07,305] [ERROR] views : Could not find a format to write the specified file in mode '?'
